apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o0dvsuz4i-go 
  janus-idp.io/tekton: o0dvsuz4i-go
  backstage.io/kubernetes-id: o0dvsuz4i-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o0dvsuz4i-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml